name: CI

on:
  push:
    branches: [ master, windows-support ]
  pull_request:
    branches: [ master ]

jobs:
  ubuntu:
    name: ubuntu-latest
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: Cache cargo
        uses: Swatinem/rust-cache@v2

      - name: Format sources
        run: cargo fmt --all

      - name: Cargo check
        run: cargo check --all-targets

      - name: Tests
        run: cargo test --all

  windows:
    name: windows-latest
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: Cache cargo
        uses: Swatinem/rust-cache@v2

      - name: Format sources
        run: cargo fmt --all

      - name: Cargo check
        run: cargo check --all-targets

      - name: Tests
        run: cargo test --all
